/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilUserUserIdRouteImport } from './routes/perfil-user/$userId'
import { Route as EditProfileUserIdRouteImport } from './routes/edit-profile/$userId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUserUserIdRoute = PerfilUserUserIdRouteImport.update({
  id: '/perfil-user/$userId',
  path: '/perfil-user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileUserIdRoute = EditProfileUserIdRouteImport.update({
  id: '/edit-profile/$userId',
  path: '/edit-profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit-profile/$userId': typeof EditProfileUserIdRoute
  '/perfil-user/$userId': typeof PerfilUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit-profile/$userId': typeof EditProfileUserIdRoute
  '/perfil-user/$userId': typeof PerfilUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit-profile/$userId': typeof EditProfileUserIdRoute
  '/perfil-user/$userId': typeof PerfilUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/edit-profile/$userId'
    | '/perfil-user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/edit-profile/$userId'
    | '/perfil-user/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/edit-profile/$userId'
    | '/perfil-user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EditProfileUserIdRoute: typeof EditProfileUserIdRoute
  PerfilUserUserIdRoute: typeof PerfilUserUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-user/$userId': {
      id: '/perfil-user/$userId'
      path: '/perfil-user/$userId'
      fullPath: '/perfil-user/$userId'
      preLoaderRoute: typeof PerfilUserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile/$userId': {
      id: '/edit-profile/$userId'
      path: '/edit-profile/$userId'
      fullPath: '/edit-profile/$userId'
      preLoaderRoute: typeof EditProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EditProfileUserIdRoute: EditProfileUserIdRoute,
  PerfilUserUserIdRoute: PerfilUserUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
