/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerfilUserRouteImport } from './routes/perfil-user'
import { Route as EditProfileRouteImport } from './routes/edit-profile'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUserRoute = PerfilUserRouteImport.update({
  id: '/perfil-user',
  path: '/perfil-user',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/edit-profile': typeof EditProfileRoute
  '/perfil-user': typeof PerfilUserRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/edit-profile': typeof EditProfileRoute
  '/perfil-user': typeof PerfilUserRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/edit-profile': typeof EditProfileRoute
  '/perfil-user': typeof PerfilUserRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/edit-profile' | '/perfil-user' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/edit-profile' | '/perfil-user' | '/register'
  id: '__root__' | '/edit-profile' | '/perfil-user' | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EditProfileRoute: typeof EditProfileRoute
  PerfilUserRoute: typeof PerfilUserRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-user': {
      id: '/perfil-user'
      path: '/perfil-user'
      fullPath: '/perfil-user'
      preLoaderRoute: typeof PerfilUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EditProfileRoute: EditProfileRoute,
  PerfilUserRoute: PerfilUserRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
